"""http://projecteuler.net/problem=002

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Solution by jontsai <hello@jontsai.com>
"""
from utils import *

EXPECTED_ANSWER = 4613732

fib_up_to_4m = fib_up_to(4000000)

numbers = filter(is_even, fib_up_to_4m)

answer = sum(numbers)

print 'Expected: %s, Answer: %s' % (EXPECTED_ANSWER, answer)
