"""http://projecteuler.net/problem=045

Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:


Triangle     Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal   Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
Hexagonal    Hn=n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Solution by jontsai <hello@jontsai.com>
"""
from utils import *

EXPECTED_ANSWER = 1533776805

n = 286
answer = None
while answer is None:
    triangle = triangle_number(n)
    if is_pentagon_num(triangle) and is_hexagon_num(triangle):
        answer = triangle
    n += 1

print 'Expected: %s, Answer: %s' % (EXPECTED_ANSWER, answer)

