/*    HTTP Host:  b.static.ak.fbcdn.net                                        */
/*    Generated:  March 31st 2009 9:59:30 AM PDT                               */
/*      Machine:  10.16.139.105                                                */
/*       Source:  Local Cache                                                  */
/*     Location:  rsrc:puvyae7f:nu_ll:/html/js/presence/iframex.js             */
/*       Locale:  nu_ll                                                        */
/*         Path:  js/presence/iframex.js                                       */


var ChannelRebuildReasons={Unknown:0,AsyncError:1,TooLong:2,Refresh:3,RefreshDelay:4,UIRestart:5,NeedSeq:6,PrevFailed:7,IFrameLoadGiveUp:8,IFrameLoadRetry:9,IFrameLoadRetryWorked:10,PageTransitionRetry:11};function fbChannelUplink(){this.startDelay=1000;this.regularDelay=100;this.checkAliveInterval=65000;this.retryInterval=1000;this.maxRetries=0;this.reconnectInterval=1000;this.maxReconnects=5;this.targetOrigin=null;this._init();}
function handleChannelParentMessageEvent(event){event=event||window.event;var domain=(event.domain||event.origin);if(domain.substring(domain.length-13)!='.facebook.com'&&domain.substring(domain.length-15)!='://facebook.com'&&domain!='facebook.com'){return;}
handleChannelParentMessage(event.data);}
function handleChannelParentMessage(parentMsgStr){if(parentMsgStr&&parentMsgStr.charAt(0)=='{'){channelUplink.handleParentMessage(eval('('+parentMsgStr+')'));}}
fbChannelUplink.prototype={_init:function(){this.debug('iframex: init');this.requestNum=0;this.request=null;this.reconnectNum=0;this.checkAliveTimer=null;this.isReconnecting=false;this.isIframeReconnecting=false;this.isActionRequest=false;this.parentAlive=false;this.channels={};this.managerIsReady=false;if(window.postMessage){var parentLoc=window.parent.location;var parentHost=parentLoc.hostname;if(parentHost=='facebook.com'||parentHost.substring(parentHost.length-13)=='.facebook.com'){this.targetOrigin=parentLoc.protocol+'//'+parentLoc.host;}
if("object"==typeof window.postMessage){var target=window.parent;this.postMessage=function(message,origin){target.postMessage(message,origin);};}else{this.postMessage=bind(window.parent,window.parent.postMessage);}
if(window.addEventListener){window.addEventListener('message',handleChannelParentMessageEvent,false);}else{window.onmessage=handleChannelParentMessageEvent;}}else if(document.postMessage){this.postMessage=bind(window.parent.document,window.parent.document.postMessage);document.addEventListener('message',handleChannelParentMessageEvent,false);}else{this.postMessage=bind(window.parent,window.parent.handleChanneliFrameMessage);}
setTimeout(function(){this.sendParentInit();}.bind(this),100);},sendParentInit:function(){this.sendParentMessage({'type':'init'});setTimeout(this.checkParentInit.bind(this),1000);},checkParentInit:function(){if(!this.parentAlive){this.sendParentInit();}},sendParentMessage:function(msg){if(this.targetOrigin){this.postMessage(JSON.encode(msg),this.targetOrigin);}else{this.postMessage(JSON.encode(msg));}},handleParentMessage:function(parentMsg){this.parentAlive=true;if(parentMsg.type=='isReady'){this.managerIsReady=parentMsg.isReady;this.isActionRequest=parentMsg.isActionRequest;if(this.managerIsReady){var channelsChanged=false;if(is_empty(parentMsg.channels)){this.channels={};this.warn('iframex: got no channels. not sending a request.');}else{var channelsChanged=false;for(var c in parentMsg.channels){if(!this.channels[c]||parentMsg.channels[c].currentSeq!=this.channels[c].currentSeq){channelsChanged=true;break;}}
this.channels=parentMsg.channels;if(!this.started){setTimeout(this.sendRequest.bind(this),this.startDelay);this.started=true;}else{if(this.isReconnecting||this.channelsChanged){this.debug('iframex: manager ready again. sending new request.');this.isReconnecting=false;this.sendRequest();}}}}}else if(parentMsg.type=='isActionRequest'){this.isActionRequest=parentMsg.isActionRequest;}},debug:function(msg){},warn:function(msg){if(window.console){if(window.console.error){window.console.error(msg);}else if(window.console.log){window.console.log(msg);}}},sendRequest:function(){var url='http://'+document.location.host+'/x/'+rand32()+'/';if(this.isActionRequest){url+='true/';this.isActionRequest=false;}else{url+='false/';}
var chan_query_params={};for(var c in this.channels){chan_query_params[encodeURIComponent(c)]=this.channels[c].currentSeq;}
url+=URI.implodeQuery(chan_query_params);clearTimeout(this.checkAliveTimer);this.requestNum++;this.checkAliveTimer=setTimeout(this.checkAlive.bind(this,this.requestNum),this.checkAliveInterval);this.request=new AsyncRequest().setHandler(this.onRequestSuccess.bind(this,this.requestNum)).setErrorHandler(this.onRequestError.bind(this,this.requestNum,false)).setTransportErrorHandler(this.onTransportError.bind(this,this.requestNum)).setMethod('GET').setReadOnly(true).setOption('retries',this.maxRetries).setOption('suppressErrorAlerts',true).setURI(url).send();},_requestIsValid:function(requestNum){if(this.isReconnecting||requestNum<this.requestNum){return false;}
if(!this.managerIsReady){this.debug("iframex: channel manager isn't ready, not sending another x request");this.isReconnecting=true;return false;}
return true;},checkAlive:function(requestNum){this.checkAliveTimer=null;if(!this._requestIsValid(requestNum)){return;}
this.warn('iframex: request took too long');if(!this.isIframeReconnecting){this.isIframeReconnecting=true;setTimeout(this.sendRequest.bind(this),this.regularDelay);}else{this.reconnect(ChannelRebuildReasons.TooLong);}},reconnect:function(reason){if(this.isReconnecting||!this.managerIsReady){return;}
this.isReconnecting=true;this.isIframeReconnecting=false;this.warn('iframex: forwarding a shutdown');var msg={type:'shutdown',reason:reason};this.sendParentMessage({'type':'channelMsg','channel':'all','seq':0,'msg':msg});},onTransportError:function(requestNum,response){this.debug('iframex: transport error');this.onRequestError(requestNum,response,true);},onRequestError:function(requestNum,response,iframeReconnectAllowed){if(!this._requestIsValid(requestNum)){return;}
this.warn('iframex: request error: '+response.getErrorDescription());this._onRequestError(ChannelRebuildReasons.AsyncError,iframeReconnectAllowed);},_onRequestError:function(reason,iframeReconnectAllowed){if(iframeReconnectAllowed&&!this.isIframeReconnecting){this.isIframeReconnecting=true;setTimeout(this.sendRequest.bind(this),this.regularDelay);return;}
this.reconnectNum++;if(this.reconnectNum>=this.maxReconnects){this.warn('iframex: too many reconnects.  bailing for good.');var msg={type:'permaShutdown'};this.sendParentMessage({'type':'channelMsg','channel':'all','seq':0,'msg':msg});}else{this.reconnect(reason);}},onRequestSuccess:function(requestNum,response){if(!this._requestIsValid(requestNum)){return;}
var channelMsg=response.getPayload();if(channelMsg.t=='refresh'){this.warn('iframex: got refresh from channel');this._onRequestError(ChannelRebuildReasons.Refresh);return;}else if(channelMsg.t=='refreshDelay'){this.warn('iframex: got refreshDelay from channel');this._onRequestError(ChannelRebuildReasons.RefreshDelay);return;}else if(channelMsg.t=='continue'){}else if(channelMsg.t=='msg'){var channel=channelMsg.c;for(var i=0;i<channelMsg.ms.length;i++){var msg=channelMsg.ms[i];var seq=this.channels[channel].currentSeq;this.sendParentMessage({'type':'channelMsg','channel':channel,'seq':seq,'msg':msg});this.channels[channel].currentSeq++;}}else{this.warn('iframex: got unexpected response from channel');this._onRequestError(ChannelRebuildReasons.AsyncError,true);return;}
this.reconnectNum=0;this.isIframeReconnecting=false;setTimeout(this.sendRequest.bind(this),this.regularDelay);}};function channelIFrameStartFn(){if(window.location.pathname.startsWith("/iframe/")){document.domain='facebook.com';window.channelUplink=new fbChannelUplink();}}
onloadRegister(channelIFrameStartFn);

if (window.Bootloader) { Bootloader.done(["js\/presence\/iframex.js"]); }